export var p_1mgk2ku = {
    "api":"http.detail.api",
    "v":"1",
    "ret":"SUCCESS",
    "data":{
        "status":{
            "code":1001,
            "msg":""
        },
        "result":{
            "liveInfo":{

            },
            "userInfo":{
                "userId":"136dz1y",
                "isLogin":false,
                "isSelf":false,
                "admin":false,
                "shopId":"1oczca",
                "sellerId":"136dz1y"
            },
            "rateLookInfo":{

            },
            "rateInfo":{
                "list":[
                    {
                        "user":{
                            "uname":"w***m",
                            "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenjuhfsggntfguzdambqhayde_160x160.jpg",
                            "profileUrl":""
                        },
                        "rateId":"118d210u",
                        "content":"衣服质量挺好的，料子很柔软舒适，做工也不错！客服态度也很好，完美",
                        "created":1560248441,
                        "isAnonymous":1,
                        "style":"颜色:杏色衬衫（送黑色裹胸） 尺码:S ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "isBuyerShow":false
                    },
                    {
                        "user":{
                            "uname":"真心的2005",
                            "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/190211_25k5060e4ac071cll881k14jl800d_132x132.jpg",
                            "profileUrl":""
                        },
                        "rateId":"118e6k5i",
                        "content":"衣服收到了，很符合我的审美观，穿起来感觉棒棒哒。",
                        "created":1560772145,
                        "isAnonymous":0,
                        "style":"颜色:杏色衬衫（送黑色裹胸） 尺码:XL ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "extraInfo":[
                            "身高: 160 cm",
                            "体重: 55 kg",
                            "是否合身: 合身 "
                        ],
                        "isBuyerShow":false,
                        "sizeInfo":{
                            "weight":"55kg",
                            "height":"160cm",
                            "desc":"合身 "
                        }
                    }
                ],
                "cRate":397,
                "imgTotal":32,
                "rateTags":[
                    {
                        "emotion":"positive",
                        "property":"图片",
                        "value":"有图片",
                        "num":32,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"款式",
                        "value":"款式好",
                        "num":21,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"质量",
                        "value":"质量很好",
                        "num":13,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"材质",
                        "value":"料子很不错",
                        "num":6,
                        "labelId":0
                    },
                    {
                        "emotion":"negative",
                        "property":"款式",
                        "value":"款式一般",
                        "num":6,
                        "labelId":0
                    },
                    {
                        "emotion":"negative",
                        "property":"描述",
                        "value":"与描述有差别",
                        "num":6,
                        "labelId":0
                    }
                ],
                "sales":2814
            },
            "itemInfo":{
                "desc":"关于亲应该拍哪个码数：80-95斤建议S码，96-110斤建议M码，111-120斤建议L码，121-130斤建议XL码，131~140斤拍XXL码，141~150斤建议XXXL码",
                "title":"女春秋季时尚套装甜美宽松V领衬衫高腰半身裙A字裙显瘦时尚套装",
                "itemId":"1mgk2ku",
                "isFaved":false,
                "isShareIntegral":false,
                "cFav":6581,
                "state":0,
                "saleStartTime":0,
                "saleType":0,
                "seo":{
                    "keywords":"女春秋季时尚套装甜美宽松V领衬衫高腰半身裙A字裙显瘦时尚套装",
                    "wap_url":"//m.mogujie.com/x6/detail/1mgk2ku",
                    "description":"来自蘑菇街优店时尚套装_套装/学生校服/工作制服_女装_服饰鞋包家关于亲应该拍哪个码数：80-95斤建议S码，96-110斤建议M码，111-120斤建议L码，121-130斤建议XL码，131~140斤拍XXL码，141~150斤建议XXXL码的女春秋季时尚套装甜美宽松V领衬衫高腰半身裙A字裙显瘦时尚套装，发现当季女装和新伊家搭配心得。",
                    "alternate":"//m.mogujie.com/x6/detail/1mgk2ku",
                    "links":"null",
                    "canonical":"//shop.mogujie.com/detail/1mgk2ku",
                    "seo_noindex":"0",
                    "title":"【女春秋季时尚套装甜美宽松V领衬衫高腰半身裙A字裙显瘦时尚套装】-女装-时尚套装_套装/学生校服/工作制服_女装_服饰鞋包-新伊家-蘑菇街优店"
                },
                "type":8,
                "priceChannel":0,
                "virtualItemType":0,
                "isMedicalBeautyVirtualItem":false,
                "isVirtualCouponItem":false,
                "isVirtualItem":false,
                "isJdItem":false,
                "inSpringFestival":false,
                "isSpringFestivalShutdownItem":false,
                "contain30DayDeliveryService":false,
                "canApplyInstallment":false,
                "extra":{
                    "sales":2814,
                    "isFreePost":true,
                    "express":"全国包邮",
                    "onSaleTime":0,
                    "isLiveSeckill":false
                },
                "officialRecommend":{

                },
                "limitDiscountInfo":{

                },
                "lowPrice":"70.00",
                "highPrice":"70.00",
                "lowNowPrice":"49.00",
                "highNowPrice":"49.00",
                "nowTime":1586845029,
                "titleTags":[

                ],
                "titleTagsV2":[

                ],
                "picTags":[

                ],
                "pickforme":{
                    "name":"帮我选",
                    "icon":"https://s10.mogucdn.com/mlcdn/c45406/191218_762ibk3def84blec68cbe4le770df_54x54.png",
                    "link":"https://h5.mogu.com/pickforme/launch/index.html?itemId=1mgk2ku&acm=3.mce.1_10_1nh28.143035.0.ky4jrrW6Y1amV.pos_0-m_547572-sd_119",
                    "acm":"3.mce.1_10_1nh28.143035.0.ky4jrrW6Y1amV.pos_0-m_547572-sd_119"
                }
            },
            "platformCoupons":{
                "bonusCount":0,
                "isBonusItem":false
            },
            "saleTextInfo":{
                "name":"slogan"
            },
            "priceInfo":{
                "nowPrice":"49.00",
                "oldPrice":"70.00",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"7折",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "diamondInfo":{
                "diamondPrice":"49.00",
                "normalPrice":"49.00",
                "state":3,
                "currency":"¥",
                "backgroundImage":"https://s11.mogucdn.com/mlcdn/c45406/170728_2740cc0db684ccfg34i2323gak715_751x81.png",
                "priceTitle":"限时优惠",
                "arrowTitle":"豪华黄钻专享价"
            },
            "normalCountdown":{
                "businessType":"",
                "isWarmUp":false,
                "nowTime":1586845029,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "shopInfo":{
                "score":[
                    {
                        "name":"描述相符",
                        "score":4.66,
                        "isBetter":false
                    },
                    {
                        "name":"质量满意",
                        "score":4.66,
                        "isBetter":false
                    }
                ],
                "services":[
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"退货补运费",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927",
                        "desc":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"延误必赔",
                        "desc":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"7天无理由退货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892",
                        "desc":"物流签收后7天内买家可无理由退货，需满足退货条件"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"全国包邮",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=895",
                        "desc":""
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"72小时发货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893",
                        "desc":""
                    }
                ],
                "categories":[
                    {
                        "name":"外套",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=209197"
                    },
                    {
                        "name":"牛仔裤",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=209200"
                    },
                    {
                        "name":"休闲裤",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=209201"
                    },
                    {
                        "name":"时尚套装",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=209204"
                    },
                    {
                        "name":"单品种草",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=209206"
                    },
                    {
                        "name":"凑单专区",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20277650"
                    },
                    {
                        "name":"毛呢外套",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20277654"
                    },
                    {
                        "name":"爆款折上折",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20277656"
                    },
                    {
                        "name":"棉服",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20277662"
                    },
                    {
                        "name":"风衣",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295945"
                    },
                    {
                        "name":"卫衣",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295946"
                    },
                    {
                        "name":"雪纺/衬衫",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295947"
                    },
                    {
                        "name":"针织/毛衣",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295949"
                    },
                    {
                        "name":"连衣裙",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295950"
                    },
                    {
                        "name":"T恤",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295952"
                    },
                    {
                        "name":"裤子",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20295953"
                    },
                    {
                        "name":"开衫",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20296928"
                    },
                    {
                        "name":"牛仔外套",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20296929"
                    },
                    {
                        "name":"半身裙",
                        "link":"http://shop.mogu.com/1oczca/list/index?categoryId=20296931"
                    }
                ],
                "cFans":"41563",
                "cSells":"26.5万",
                "isMarked":false,
                "cGoods":361,
                "userId":"136dz1y",
                "shopLogo":"https://s11.mogucdn.com/mlcdn/c45406/200317_3593kadgf9b3jk6ab1ae31h0e0gld_200x200.jpg",
                "name":"新伊家",
                "shopId":"1oczca",
                "type":1,
                "level":4,
                "levelDescV2":"推荐指数",
                "shopUrl":"//m.mogu.com/v8/meili/shop?shopid=1oczca",
                "saleDesc":"在架商品 ",
                "saleDescV2":"在架商品 361",
                "shopLabels":[
                    {
                        "id":201,
                        "text":"4.1万人关注"
                    },
                    {
                        "id":303,
                        "text":"累计销量26.5万+"
                    },
                    {
                        "id":602,
                        "text":"3年老字号"
                    }
                ],
                "dynShopLabels":[

                ],
                "shopLabelPriority":"101,102,201,301,302,303,401,402,501,502,601,602"
            },
            "preSaleInfo":"",
            "detailInfo":{
                "splitDetailImage":true,
                "desc":"关于亲应该拍哪个码数：80-95斤建议S码，96-110斤建议M码，111-120斤建议L码，121-130斤建议XL码，131~140斤拍XXL码，141~150斤建议XXXL码",
                "detailImage":[
                    {
                        "desc":"",
                        "key":"穿着效果",
                        "anchor":"model_img",
                        "list":[
                            "https://s5.mogucdn.com/mlcdn/c45406/190507_1ggbe0g0352fed29icg0g43blj464_640x960.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190507_4519g16d6ckjg69fked2d1651caa1_640x960.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190507_7gj7i89g45j24e2hc63ga2699h48j_640x960.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190507_64g4kelcdg9d5cb0kg37c4cci8a05_640x960.jpg"
                        ]
                    },
                    {
                        "desc":"",
                        "key":"整体款式",
                        "anchor":"baipai_img2",
                        "list":[
                            "https://s5.mogucdn.com/mlcdn/c45406/190507_3hbi5j3jaaihc39d2cl228l9jgkd1_640x960.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190507_2f7lac5e5d075i4878c0bh1eg2j05_640x960.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190507_1g91j5k7kf2bj0h470all1e2d0ck9_640x960.jpg"
                        ]
                    },
                    {
                        "desc":"厂家出厂验货，仓库验货，包装员验货，我们每个商品都有经过3验再配货包装！ 请菇凉放心购物！",
                        "key":"包装展示",
                        "anchor":"package_info"
                    },
                    {
                        "desc":"为了让菇凉们可以在蘑菇街无忧购物，我们为您提供了两大保障：1、我们支持七天无理由退换货，只要不影响二次销售，在收到货hou七天内都可以正常退换货。2、我们为菇凉购买了运费险，您申请退货hou，退货的邮费您先垫付，然后把物流单号填到退货流程中，邮费在订单退货完成hou打自您的蘑菇钱包上，这个运费是蘑菇街合作的保险公司发的，不是商家发的哦！",
                        "key":"服务说明",
                        "anchor":"service_info"
                    },
                    {
                        "desc":"谢谢对我们的支持！新伊家专注时尚女装，韩版，学院，小清新，原宿风，各种流行、网红服装，欢迎关注我们！",
                        "key":"店铺信息",
                        "anchor":"shop_info",
                        "list":[
                            "https://s11.mogucdn.com/mlcdn/c024f5/190417_2d51ljj2a42lddkg49ibag494g3ca_1125x540.png"
                        ]
                    }
                ]
            },
            "countdownInfo":{
                "businessType":"NORMAL",
                "isWarmUp":false,
                "nowTime":1586845029,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "topImages":[
                "https://s11.mogucdn.com/mlcdn/c45406/190507_6fgf037g25f63i29286j95ba8h2di_640x960.jpg"
            ],
            "normalShareInfo":{
                "title":"女春秋季时尚套装甜美宽松V领衬衫高腰半身裙A字裙显瘦时尚套装",
                "content":"亲爱的～这件宝贝不错哦，快进来看看吧～",
                "url":"//h5.mogu.com/detail-normal/index.html?itemId=1mgk2ku&from=share",
                "imageUrl":"https://s11.mogucdn.com/mlcdn/c45406/190507_6fgf037g25f63i29286j95ba8h2di_640x960.jpg"
            },
            "itemParams":{
                "info":{
                    "set":{
                        "图案":"纯色",
                        "厚薄":"普通",
                        "颜色":"白色衬衫（送黑色吊带）,侧开叉半身裙,杏色衬衫（送黑色吊带）",
                        "袖型":"常规袖",
                        "尺码":"S,XL,L,M,XXL,XXXL",
                        "衣长":"常规款（51-65cm）",
                        "季节":"春秋",
                        "材质":"其他",
                        "领型":"V领",
                        "袖长":"五分袖（中袖）",
                        "款式":"衣裙套装",
                        "风格":"甜美",
                        "潮流":"韩系"
                    },
                    "key":"产品参数",
                    "anchor":"product_info"
                },
                "rule":{
                    "desc":"由于测量方式不同，可能存在偏差，尺码仅供参考，按平时穿着码数购买即可，谢谢支持！",
                    "tables":[
                        [
                            [
                                "尺码",
                                "胸围",
                                "裙长"
                            ],
                            [
                                "S",
                                "100",
                                "39.5"
                            ],
                            [
                                "M",
                                "102",
                                "40"
                            ],
                            [
                                "L",
                                "106",
                                "40.5"
                            ],
                            [
                                "XL",
                                "110",
                                "41"
                            ],
                            [
                                "XXL",
                                "114",
                                "41.5"
                            ],
                            [
                                "XXXL",
                                "118",
                                "42"
                            ]
                        ]
                    ],
                    "key":"尺码说明",
                    "anchor":"size_info",
                    "disclaimer":"※ 以上尺寸为实物人工测量，因测量方式不同会有1-2cm误差，相关数据仅作参考，以收到实物为准。"
                }
            },
            "normalPrice":{
                "nowPrice":"49.00",
                "oldPrice":"70.00",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"7折",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "itemServices":{
                "services":[
                    {
                        "name":"72小时发货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893"
                    },
                    {
                        "name":"7天无理由退货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"物流签收后7天内买家可无理由退货，需满足退货条件",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892"
                    },
                    {
                        "name":"延误必赔",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "name":"退货补运费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927"
                    },
                    {
                        "name":"白付美分期购",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"白付美分期购：在我的钱包 →白付美页面开通即可使用分期购。本月消费，分3/6/12期还款，每月只还一点点，轻松享受大牌好货。（分12期只对部分用户开放。）"
                    },
                    {
                        "name":"全国包邮",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=895"
                    }
                ],
                "columns":[
                    {
                        "name":"sales",
                        "desc":"销量 2814",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    },
                    {
                        "name":"express",
                        "desc":"免邮费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    }
                ]
            },
            "skuInfo":{
                "itemId":"1mgk2ku",
                "img":"https://s11.mogucdn.com/mlcdn/c45406/190507_6fgf037g25f63i29286j95ba8h2di_640x960.jpg",
                "isJdItem":false,
                "title":"女春秋季时尚套装甜美宽松V领衬衫高腰半身裙A字裙显瘦时尚套装",
                "skus":[
                    {
                        "stockId":"119vvp8m",
                        "xdSkuId":"119vvp8m",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/190507_7ecl34ik15l3h5dicbef02ef23g9g_640x960.jpg",
                        "currency":"¥",
                        "stock":211,
                        "style":"侧开叉半身裙",
                        "color":"",
                        "size":"S",
                        "styleId":1,
                        "sizeId":100
                    },
                    {
                        "stockId":"119vvp8o",
                        "xdSkuId":"119vvp8o",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/190507_7ecl34ik15l3h5dicbef02ef23g9g_640x960.jpg",
                        "currency":"¥",
                        "stock":188,
                        "style":"侧开叉半身裙",
                        "color":"",
                        "size":"M",
                        "styleId":1,
                        "sizeId":101
                    },
                    {
                        "stockId":"119vvp8q",
                        "xdSkuId":"119vvp8q",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/190507_7ecl34ik15l3h5dicbef02ef23g9g_640x960.jpg",
                        "currency":"¥",
                        "stock":199,
                        "style":"侧开叉半身裙",
                        "color":"",
                        "size":"L",
                        "styleId":1,
                        "sizeId":102
                    },
                    {
                        "stockId":"119vvp8s",
                        "xdSkuId":"119vvp8s",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/190507_7ecl34ik15l3h5dicbef02ef23g9g_640x960.jpg",
                        "currency":"¥",
                        "stock":213,
                        "style":"侧开叉半身裙",
                        "color":"",
                        "size":"XL",
                        "styleId":1,
                        "sizeId":103
                    },
                    {
                        "stockId":"119vvp8u",
                        "xdSkuId":"119vvp8u",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/190507_7ecl34ik15l3h5dicbef02ef23g9g_640x960.jpg",
                        "currency":"¥",
                        "stock":246,
                        "style":"侧开叉半身裙",
                        "color":"",
                        "size":"XXL",
                        "styleId":1,
                        "sizeId":104
                    },
                    {
                        "stockId":"11amxel0",
                        "xdSkuId":"11amxel0",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/190507_7ecl34ik15l3h5dicbef02ef23g9g_640x960.jpg",
                        "currency":"¥",
                        "stock":0,
                        "style":"侧开叉半身裙",
                        "color":"",
                        "size":"XXXL",
                        "styleId":1,
                        "sizeId":105
                    },
                    {
                        "stockId":"11amxel2",
                        "xdSkuId":"11amxel2",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_6e3li538el8ebid93hca43ef2ihk8_640x960.jpg",
                        "currency":"¥",
                        "stock":129,
                        "style":"杏色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"S",
                        "styleId":2,
                        "sizeId":100
                    },
                    {
                        "stockId":"11amxel6",
                        "xdSkuId":"11amxel6",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_6e3li538el8ebid93hca43ef2ihk8_640x960.jpg",
                        "currency":"¥",
                        "stock":62,
                        "style":"杏色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"M",
                        "styleId":2,
                        "sizeId":101
                    },
                    {
                        "stockId":"11amxel4",
                        "xdSkuId":"11amxel4",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_6e3li538el8ebid93hca43ef2ihk8_640x960.jpg",
                        "currency":"¥",
                        "stock":131,
                        "style":"杏色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"L",
                        "styleId":2,
                        "sizeId":102
                    },
                    {
                        "stockId":"11amxel8",
                        "xdSkuId":"11amxel8",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_6e3li538el8ebid93hca43ef2ihk8_640x960.jpg",
                        "currency":"¥",
                        "stock":38,
                        "style":"杏色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"XL",
                        "styleId":2,
                        "sizeId":103
                    },
                    {
                        "stockId":"11amxela",
                        "xdSkuId":"11amxela",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_6e3li538el8ebid93hca43ef2ihk8_640x960.jpg",
                        "currency":"¥",
                        "stock":112,
                        "style":"杏色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"XXL",
                        "styleId":2,
                        "sizeId":104
                    },
                    {
                        "stockId":"11amxelc",
                        "xdSkuId":"11amxelc",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_6e3li538el8ebid93hca43ef2ihk8_640x960.jpg",
                        "currency":"¥",
                        "stock":153,
                        "style":"杏色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"XXXL",
                        "styleId":2,
                        "sizeId":105
                    },
                    {
                        "stockId":"11amxele",
                        "xdSkuId":"11amxele",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_7ef4l51lb701fj8869921kjela534_640x960.jpg",
                        "currency":"¥",
                        "stock":152,
                        "style":"白色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"S",
                        "styleId":3,
                        "sizeId":100
                    },
                    {
                        "stockId":"11amxelg",
                        "xdSkuId":"11amxelg",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_7ef4l51lb701fj8869921kjela534_640x960.jpg",
                        "currency":"¥",
                        "stock":126,
                        "style":"白色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"M",
                        "styleId":3,
                        "sizeId":101
                    },
                    {
                        "stockId":"11amxeli",
                        "xdSkuId":"11amxeli",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_7ef4l51lb701fj8869921kjela534_640x960.jpg",
                        "currency":"¥",
                        "stock":147,
                        "style":"白色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"L",
                        "styleId":3,
                        "sizeId":102
                    },
                    {
                        "stockId":"11amxelk",
                        "xdSkuId":"11amxelk",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_7ef4l51lb701fj8869921kjela534_640x960.jpg",
                        "currency":"¥",
                        "stock":158,
                        "style":"白色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"XL",
                        "styleId":3,
                        "sizeId":103
                    },
                    {
                        "stockId":"11amxelm",
                        "xdSkuId":"11amxelm",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_7ef4l51lb701fj8869921kjela534_640x960.jpg",
                        "currency":"¥",
                        "stock":188,
                        "style":"白色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"XXL",
                        "styleId":3,
                        "sizeId":104
                    },
                    {
                        "stockId":"11amxelo",
                        "xdSkuId":"11amxelo",
                        "price":7000,
                        "nowprice":4900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190706_7ef4l51lb701fj8869921kjela534_640x960.jpg",
                        "currency":"¥",
                        "stock":189,
                        "style":"白色衬衫（送黑色吊带）",
                        "color":"",
                        "size":"XXXL",
                        "styleId":3,
                        "sizeId":105
                    }
                ],
                "props":[
                    {
                        "label":"颜色",
                        "list":[
                            {
                                "default":false,
                                "styleId":1,
                                "name":"侧开叉半身裙",
                                "index":1,
                                "type":"style"
                            },
                            {
                                "default":false,
                                "styleId":2,
                                "name":"杏色衬衫（送黑色吊带）",
                                "index":2,
                                "type":"style"
                            },
                            {
                                "default":false,
                                "styleId":3,
                                "name":"白色衬衫（送黑色吊带）",
                                "index":3,
                                "type":"style"
                            }
                        ],
                        "isDefault":false
                    },
                    {
                        "label":"尺码",
                        "list":[
                            {
                                "sizeId":100,
                                "default":false,
                                "name":"S",
                                "index":100,
                                "type":"size"
                            },
                            {
                                "sizeId":101,
                                "default":false,
                                "name":"M",
                                "index":101,
                                "type":"size"
                            },
                            {
                                "sizeId":102,
                                "default":false,
                                "name":"L",
                                "index":102,
                                "type":"size"
                            },
                            {
                                "sizeId":103,
                                "default":false,
                                "name":"XL",
                                "index":103,
                                "type":"size"
                            },
                            {
                                "sizeId":104,
                                "default":false,
                                "name":"XXL",
                                "index":104,
                                "type":"size"
                            },
                            {
                                "sizeId":105,
                                "default":false,
                                "name":"XXXL",
                                "index":105,
                                "type":"size"
                            }
                        ],
                        "isDefault":false
                    }
                ],
                "styleKey":"颜色",
                "sizeKey":"尺码",
                "priceRange":"¥49.00",
                "defaultPrice":"¥49.00",
                "totalStock":2642,
                "canInstallment":false,
                "addressInfo":{

                }
            }
        }
    },
    "needHeaderCookie":false
}
