export var p_1m7rtj4 = {
    "api":"http.detail.api",
    "v":"1",
    "ret":"SUCCESS",
    "data":{
        "status":{
            "code":1001,
            "msg":""
        },
        "result":{
            "liveInfo":{

            },
            "userInfo":{
                "userId":"1d85my",
                "isLogin":false,
                "isSelf":false,
                "admin":false,
                "shopId":"14q2a",
                "sellerId":"1d85my"
            },
            "rateLookInfo":{

            },
            "rateInfo":{
                "list":[
                    {
                        "user":{
                            "uname":"凹***吧",
                            "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenbygrsggntfguzdambqhayde_160x160.jpg",
                            "profileUrl":""
                        },
                        "rateId":"1184g8ky",
                        "content":"薄度不错，也不勒肚子，裤腿不会太长，穿起来比较时尚，买了两条",
                        "created":1557046122,
                        "isAnonymous":1,
                        "style":"颜色:黑色 尺码:均码 ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "extraInfo":[
                            "身高: 163 cm",
                            "体重: 47 kg",
                            "是否合身: 合身 "
                        ],
                        "isBuyerShow":false,
                        "sizeInfo":{
                            "weight":"47kg",
                            "height":"163cm",
                            "desc":"合身 "
                        }
                    },
                    {
                        "user":{
                            "uname":"凹***吧",
                            "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenbygrsggntfguzdambqhayde_160x160.jpg",
                            "profileUrl":""
                        },
                        "rateId":"1184g8kw",
                        "content":"薄度不错，也不勒肚子，裤腿不会太长，穿起来比较时尚",
                        "created":1557046122,
                        "isAnonymous":1,
                        "style":"颜色:深灰色 尺码:均码 ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "extraInfo":[
                            "身高: 163 cm",
                            "体重: 47 kg",
                            "是否合身: 合身 "
                        ],
                        "isBuyerShow":false,
                        "sizeInfo":{
                            "weight":"47kg",
                            "height":"163cm",
                            "desc":"合身 "
                        }
                    }
                ],
                "cRate":1463,
                "imgTotal":94,
                "rateTags":[
                    {
                        "emotion":"positive",
                        "property":"图片",
                        "value":"有图片",
                        "num":94,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"材质",
                        "value":"料子很不错",
                        "num":55,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"质量",
                        "value":"质量很好",
                        "num":40,
                        "labelId":0
                    },
                    {
                        "emotion":"negative",
                        "property":"厚度",
                        "value":"有点薄",
                        "num":18,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"性价比",
                        "value":"性价比高",
                        "num":17,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"款式",
                        "value":"款式好",
                        "num":15,
                        "labelId":0
                    }
                ],
                "sales":5763
            },
            "itemInfo":{
                "desc":"兔子说：高弹力莫代尔棉的显瘦打底裤，全新面料，本款采用95%精棉+5%氨纶精制而成，既保证了裤子的亲肤健康度，又能弹性自如，让整体舒适自然！胖瘦都可以穿。好裤子不嫌多，实惠冲量，多买几条替换着穿哦~ 【建议体重：80-140斤】",
                "title":"莫代尔打底裤子女外穿薄款显瘦韩版学生百搭2020春季新款修身铅笔小脚裤弹力纯棉高腰紧身裤",
                "itemId":"1m7rtj4",
                "isFaved":false,
                "isShareIntegral":false,
                "cFav":3951,
                "state":0,
                "saleStartTime":0,
                "saleType":0,
                "seo":{
                    "keywords":"莫代尔打底裤子女外穿薄款显瘦韩版学生百搭2020春季新款修身铅笔小脚裤弹力纯棉高腰紧身裤",
                    "wap_url":"//m.mogujie.com/x6/detail/1m7rtj4",
                    "description":"来自蘑菇街优店裤子_打底裤_女装_服饰鞋包家兔子说：高弹力莫代尔棉的显瘦打底裤，全新面料，本款采用95%精棉+5%氨纶精制而成，既保证了裤子的亲肤健康度，又能弹性自如，让整体舒适自然！胖瘦都可以穿。好裤子不嫌多，实惠冲量，多买几条替换着穿哦~ 【建议体重：80-140斤】的莫代尔打底裤子女外穿薄款显瘦韩版学生百搭2020春季新款修身铅笔小脚裤弹力纯棉高腰紧身裤，发现当季女装和贝琳美旗舰店搭配心得。",
                    "alternate":"//m.mogujie.com/x6/detail/1m7rtj4",
                    "links":"null",
                    "canonical":"//shop.mogujie.com/detail/1m7rtj4",
                    "seo_noindex":"0",
                    "title":"【莫代尔打底裤子女外穿薄款显瘦韩版学生百搭2020春季新款修身铅笔小脚裤弹力纯棉高腰紧身裤】-女装-裤子_打底裤_女装_服饰鞋包-贝琳美旗舰店-蘑菇街优店"
                },
                "type":8,
                "video":{
                    "cover":"https://s5.mogucdn.com/mlcdn/c45406/181212_8h851e635alg63kl33l4f6c96h974_640x960.jpg",
                    "videoId":1021269
                },
                "priceChannel":0,
                "virtualItemType":0,
                "isMedicalBeautyVirtualItem":false,
                "isVirtualCouponItem":false,
                "isVirtualItem":false,
                "isJdItem":false,
                "inSpringFestival":false,
                "isSpringFestivalShutdownItem":false,
                "contain30DayDeliveryService":false,
                "canApplyInstallment":false,
                "extra":{
                    "sales":5764,
                    "isFreePost":true,
                    "express":"全国包邮",
                    "address":"浙江金华",
                    "onSaleTime":0,
                    "isLiveSeckill":false
                },
                "officialRecommend":{

                },
                "limitDiscountInfo":{

                },
                "lowPrice":"38.50",
                "highPrice":"38.50",
                "lowNowPrice":"26.90",
                "highNowPrice":"26.90",
                "brandName":"贝琳美",
                "nowTime":1586845477,
                "titleTags":[

                ],
                "titleTagsV2":[

                ],
                "picTags":[

                ],
                "pickforme":{
                    "name":"帮我选",
                    "icon":"https://s10.mogucdn.com/mlcdn/c45406/191218_762ibk3def84blec68cbe4le770df_54x54.png",
                    "link":"https://h5.mogu.com/pickforme/launch/index.html?itemId=1m7rtj4&acm=3.mce.1_10_1nh28.143035.0.ky4jrrW6ZUaPl.pos_0-m_547572-sd_119",
                    "acm":"3.mce.1_10_1nh28.143035.0.ky4jrrW6ZUaPl.pos_0-m_547572-sd_119"
                }
            },
            "platformCoupons":{
                "bonusCount":0,
                "isBonusItem":false
            },
            "saleTextInfo":{
                "name":"slogan"
            },
            "priceInfo":{
                "nowPrice":"26.90",
                "oldPrice":"38.50",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"新春钜惠",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "diamondInfo":{
                "diamondPrice":"26.90",
                "normalPrice":"26.90",
                "state":3,
                "currency":"¥",
                "backgroundImage":"https://s11.mogucdn.com/mlcdn/c45406/170728_2740cc0db684ccfg34i2323gak715_751x81.png",
                "priceTitle":"限时优惠",
                "arrowTitle":"豪华黄钻专享价"
            },
            "normalCountdown":{
                "businessType":"",
                "isWarmUp":false,
                "nowTime":1586845477,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "shopInfo":{
                "score":[
                    {
                        "name":"描述相符",
                        "score":4.7,
                        "isBetter":false
                    },
                    {
                        "name":"质量满意",
                        "score":4.7,
                        "isBetter":false
                    }
                ],
                "services":[
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"退货补运费",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927",
                        "desc":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"延误必赔",
                        "desc":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"7天无理由退货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892",
                        "desc":"物流签收后7天内买家可无理由退货，需满足退货条件"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"全国包邮",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=895",
                        "desc":""
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"72小时发货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893",
                        "desc":""
                    }
                ],
                "categories":[
                    {
                        "name":"人气推荐",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=23783"
                    },
                    {
                        "name":"打底裤",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=66078"
                    },
                    {
                        "name":"休闲裤",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=76804"
                    },
                    {
                        "name":"其它",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=20170886"
                    },
                    {
                        "name":"春夏新品裤",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=20230361"
                    },
                    {
                        "name":"短裤",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=20299057"
                    },
                    {
                        "name":"上衣",
                        "link":"http://shop.mogu.com/14q2a/list/index?categoryId=20360350"
                    }
                ],
                "cFans":"85307",
                "cSells":"45.5万",
                "isMarked":false,
                "cGoods":98,
                "userId":"1d85my",
                "shopLogo":"https://s5.mogucdn.com/mlcdn/c45406/200309_2blgk8he0eh49a3f5b883ll6eb656_200x200.jpg",
                "name":"贝琳美旗舰店",
                "shopId":"14q2a",
                "type":1,
                "level":3,
                "levelDescV2":"推荐指数",
                "shopUrl":"//m.mogu.com/v8/meili/shop?shopid=14q2a",
                "saleDesc":"在架商品 ",
                "saleDescV2":"在架商品 98",
                "shopLabels":[
                    {
                        "id":201,
                        "text":"8.5万人关注"
                    },
                    {
                        "id":303,
                        "text":"累计销量45.4万+"
                    },
                    {
                        "id":601,
                        "text":"5年金招牌"
                    }
                ],
                "dynShopLabels":[

                ],
                "shopLabelPriority":"101,102,201,301,302,303,401,402,501,502,601,602"
            },
            "preSaleInfo":"",
            "detailInfo":{
                "splitDetailImage":true,
                "desc":"兔子说：高弹力莫代尔棉的显瘦打底裤，全新面料，本款采用95%精棉+5%氨纶精制而成，既保证了裤子的亲肤健康度，又能弹性自如，让整体舒适自然！胖瘦都可以穿。好裤子不嫌多，实惠冲量，多买几条替换着穿哦~ 【建议体重：80-140斤】",
                "detailImage":[
                    {
                        "desc":"",
                        "key":"穿着效果",
                        "anchor":"model_img",
                        "list":[
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_895k697i7djggefjd583kc6bg3h38_790x889.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_6j9dcl9hdf239ej8h717dkk3i216c_790x586.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_004d78a173gbe4ck0hjk45a8lg814_790x1084.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_6aka649g9gdg7fl5g6b1a09g1j345_790x969.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_7b3eb43l26hb4a8ga446heh14a46b_790x838.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_5410l75gg7ckb9l0k42al2b0e0125_790x625.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_12lh75kijhb72bb2c9476175661h2_790x1186.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_4fhk8c8ekg9ck928690jc6844630c_790x931.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_30djb673ke2b30597f0akj5158k40_790x713.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_476d383i97k6e6d95219hll0eci4h_790x438.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_6j0f9fggb4bh5f51bk1b3fbacjefi_790x996.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_225g9ja07fcgilcjci5d2ifj3gjgd_790x395.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_65fale9g15043lhfh7h31la08d5cb_790x691.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_4a8jkh32c8l8a5k60d9afk12b25eb_790x606.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_4lffigll7k5f737elidij2849k4kk_790x572.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_27jf90bd816j60g36j065hc19a70g_790x1114.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_5cijka541lik65hadc7bi8c589jee_790x1326.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_49dkdgj07akedi800c73ak9fjjk8l_790x1052.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_1gfh0f0l3g428c69hljeg7h8ikf1b_790x1353.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_5kb1acgh084c432c4dhb3e6je6d14_790x1000.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_72g2bi7lldb3b9haeb77kfa2bck5g_790x1054.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_4cdgb783jjk746862a1g2bld94a4h_790x800.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/180828_6592dh1fd4ad4gk1abc1a6ga7007f_790x976.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/180828_0a52iakcfef9ag0d5f0b82lc437k5_790x749.jpg"
                        ]
                    },
                    {
                        "desc":"独立新潮的外贸品牌，深受年轻女性的喜爱。淋漓的前沿元素和优雅古风的结合使兔子家女装魅力四溢。在设计上融合了欧美、日韩等流行时尚元素，使简单而不单调，个性而不张扬。如果说清新优雅的姿态是她外表美，那么无疑每个消费者的体验都是对她的肯定就是她的内在表现。我们注重每一款衣服的设计理念，以合理的价格带给您丰富的体验。",
                        "key":"品牌介绍",
                        "anchor":"brand_info",
                        "list":[
                            "https://s11.mogucdn.com/mlcdn/c024f5/190417_2d51ljj2a42lddkg49ibag494g3ca_1125x540.png"
                        ]
                    }
                ]
            },
            "countdownInfo":{
                "businessType":"NORMAL",
                "isWarmUp":false,
                "nowTime":1586845477,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "topImages":[
                "https://s5.mogucdn.com/mlcdn/c45406/180828_38873ea7338e5ecgi45ke8lcd5942_640x960.jpg",
                "https://s5.mogucdn.com/mlcdn/c45406/180828_0l89b1a6ic10a1c8232ii46d92dfh_640x960.jpg",
                "https://s5.mogucdn.com/mlcdn/c45406/180828_0b7ala178g47i4336kld7e93c9c1a_640x960.jpg",
                "https://s5.mogucdn.com/mlcdn/c45406/180828_6jhg441dci4c1l7i8h5gil59217j2_640x960.jpg",
                "https://s11.mogucdn.com/mlcdn/c45406/180828_82865k50f29llgh07acf4b385i6cl_640x960.jpg"
            ],
            "normalShareInfo":{
                "title":"莫代尔打底裤子女外穿薄款显瘦韩版学生百搭2020春季新款修身铅笔小脚裤弹力纯棉高腰紧身裤",
                "content":"亲爱的～这件宝贝不错哦，快进来看看吧～",
                "url":"//h5.mogu.com/detail-normal/index.html?itemId=1m7rtj4&from=share",
                "imageUrl":"https://s5.mogucdn.com/mlcdn/c45406/180828_38873ea7338e5ecgi45ke8lcd5942_640x960.jpg"
            },
            "itemParams":{
                "info":{
                    "set":{
                        "图案":"纯色",
                        "厚薄":"常规",
                        "颜色":"黑色,深灰色,浅灰色",
                        "裤长":"九分裤",
                        "尺码":"均码",
                        "版型":"紧身",
                        "季节":"春秋",
                        "材质":"纯棉",
                        "元素":"松紧,柔软洗",
                        "腰线高度":"高腰",
                        "风格":"运动休闲",
                        "闭合方式":"皮筋腰带",
                        "潮流":"韩系"
                    },
                    "key":"产品参数",
                    "anchor":"product_info"
                },
                "rule":{
                    "tables":[
                        [
                            [
                                "尺码",
                                "腰围",
                                "臀围",
                                "裤长"
                            ],
                            [
                                "均码",
                                "54（弹力）",
                                "66-116",
                                "90"
                            ]
                        ]
                    ],
                    "key":"尺码说明",
                    "anchor":"size_info",
                    "disclaimer":"※ 以上尺寸为实物人工测量，因测量方式不同会有1-2cm误差，相关数据仅作参考，以收到实物为准。"
                }
            },
            "normalPrice":{
                "nowPrice":"26.90",
                "oldPrice":"38.50",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"新春钜惠",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "itemServices":{
                "services":[
                    {
                        "name":"品牌认证",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"严格审核，正规品牌授权链；精挑细选，国内外知名品牌合作。引领潮流趋势，时尚品质保证。"
                    },
                    {
                        "name":"72小时发货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893"
                    },
                    {
                        "name":"7天无理由退货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"物流签收后7天内买家可无理由退货，需满足退货条件",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892"
                    },
                    {
                        "name":"延误必赔",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "name":"退货补运费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927"
                    },
                    {
                        "name":"白付美分期购",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"白付美分期购：在我的钱包 →白付美页面开通即可使用分期购。本月消费，分3/6/12期还款，每月只还一点点，轻松享受大牌好货。（分12期只对部分用户开放。）"
                    },
                    {
                        "name":"全国包邮",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=895"
                    }
                ],
                "columns":[
                    {
                        "name":"sales",
                        "desc":"销量 5764",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    },
                    {
                        "name":"express",
                        "desc":"免邮费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    }
                ]
            },
            "skuInfo":{
                "itemId":"1m7rtj4",
                "img":"https://s5.mogucdn.com/mlcdn/c45406/180828_38873ea7338e5ecgi45ke8lcd5942_640x960.jpg",
                "isJdItem":false,
                "title":"莫代尔打底裤子女外穿薄款显瘦韩版学生百搭2020春季新款修身铅笔小脚裤弹力纯棉高腰紧身裤",
                "skus":[
                    {
                        "stockId":"116n09q0",
                        "xdSkuId":"116n09q0",
                        "price":3850,
                        "nowprice":2690,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/180828_1ghg7alkl26d1444ha8i9dab6g838_640x960.jpg",
                        "currency":"¥",
                        "stock":8139,
                        "style":"黑色",
                        "color":"#000000",
                        "size":"均码",
                        "styleId":1,
                        "sizeId":100
                    },
                    {
                        "stockId":"116n09q2",
                        "xdSkuId":"116n09q2",
                        "price":3850,
                        "nowprice":2690,
                        "img":"https://s5.mogucdn.com/mlcdn/c45406/180828_688ge94ci1bgfb0ihba1k490h284c_640x960.jpg",
                        "currency":"¥",
                        "stock":8813,
                        "style":"浅灰色",
                        "color":"",
                        "size":"均码",
                        "styleId":2,
                        "sizeId":100
                    },
                    {
                        "stockId":"116n09q4",
                        "xdSkuId":"116n09q4",
                        "price":3850,
                        "nowprice":2690,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/180828_7jchl58ebfia9l82e0f8j1632859f_640x960.jpg",
                        "currency":"¥",
                        "stock":8132,
                        "style":"深灰色",
                        "color":"",
                        "size":"均码",
                        "styleId":3,
                        "sizeId":100
                    }
                ],
                "props":[
                    {
                        "label":"颜色",
                        "list":[
                            {
                                "default":false,
                                "styleId":1,
                                "name":"黑色",
                                "index":1,
                                "type":"style"
                            },
                            {
                                "default":false,
                                "styleId":2,
                                "name":"浅灰色",
                                "index":2,
                                "type":"style"
                            },
                            {
                                "default":false,
                                "styleId":3,
                                "name":"深灰色",
                                "index":3,
                                "type":"style"
                            }
                        ],
                        "isDefault":false
                    },
                    {
                        "label":"尺码",
                        "list":[
                            {
                                "sizeId":100,
                                "default":false,
                                "name":"均码",
                                "index":100,
                                "type":"size"
                            }
                        ],
                        "isDefault":false
                    }
                ],
                "styleKey":"颜色",
                "sizeKey":"尺码",
                "priceRange":"¥26.90",
                "defaultPrice":"¥26.90",
                "totalStock":25084,
                "canInstallment":false,
                "addressInfo":{

                }
            }
        }
    },
    "needHeaderCookie":false
}
