export var p_1me7hv4 = {
    "api":"http.detail.api",
    "v":"1",
    "ret":"SUCCESS",
    "data":{
        "status":{
            "code":1001,
            "msg":""
        },
        "result":{
            "liveInfo":{

            },
            "userInfo":{
                "userId":"17dn21e",
                "isLogin":false,
                "isSelf":false,
                "admin":false,
                "shopId":"1172uj7q",
                "sellerId":"17dn21e"
            },
            "rateLookInfo":{

            },
            "rateInfo":{
                "list":[
                    {
                        "user":{
                            "uname":"w***d",
                            "avatar":"https://s11.mogucdn.com/p1/160105/idid_ifrtmoddmnsggntfguzdambqhayde_160x160.jpg",
                            "profileUrl":""
                        },
                        "rateId":"117ywo16",
                        "content":"牛仔连衣裙面料柔软，款式时尚，穿着修身显瘦，质量好尺码标准",
                        "created":1555216444,
                        "isAnonymous":1,
                        "style":"颜色:浅蓝色 尺码:XL ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "isBuyerShow":false
                    },
                    {
                        "user":{
                            "uname":"wx_dt549ykufjcxw",
                            "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/171016_725icd1kfdbd7h4j61181k9c72h17_640x640.jpg",
                            "profileUrl":""
                        },
                        "rateId":"117zx71c",
                        "content":"莲衣裙很漂亮，质量很好，穿在身上很显瘦，有气质，非常喜欢。",
                        "created":1555483673,
                        "isAnonymous":0,
                        "style":"颜色:浅蓝色 尺码:M ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "extraInfo":[
                            "身高: 165 cm",
                            "体重: 45 kg",
                            "是否合身: 合身 "
                        ],
                        "isBuyerShow":false,
                        "sizeInfo":{
                            "weight":"45kg",
                            "height":"165cm",
                            "desc":"合身 "
                        }
                    }
                ],
                "cRate":41,
                "imgTotal":1,
                "rateTags":[
                    {
                        "emotion":"positive",
                        "property":"图片",
                        "value":"有图片",
                        "num":1,
                        "labelId":0
                    },
                    {
                        "emotion":"positive",
                        "property":"款式",
                        "value":"款式好",
                        "num":3,
                        "labelId":0
                    }
                ],
                "sales":247
            },
            "itemInfo":{
                "desc":"牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子",
                "title":"牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子",
                "itemId":"1me7hv4",
                "isFaved":false,
                "isShareIntegral":false,
                "cFav":1765,
                "state":0,
                "saleStartTime":0,
                "saleType":0,
                "seo":{
                    "keywords":"牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子",
                    "wap_url":"//m.mogujie.com/x6/detail/1me7hv4",
                    "description":"来自蘑菇街优店女装_服饰鞋包_连衣裙_裙子家牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子的牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子，发现当季女装和春风十里只为你搭配心得。",
                    "alternate":"//m.mogujie.com/x6/detail/1me7hv4",
                    "links":"null",
                    "canonical":"//shop.mogujie.com/detail/1me7hv4",
                    "seo_noindex":"0",
                    "title":"【牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子】-女装-女装_服饰鞋包_连衣裙_裙子-春风十里只为你-蘑菇街优店"
                },
                "type":8,
                "priceChannel":0,
                "virtualItemType":0,
                "isMedicalBeautyVirtualItem":false,
                "isVirtualCouponItem":false,
                "isVirtualItem":false,
                "isJdItem":false,
                "inSpringFestival":false,
                "isSpringFestivalShutdownItem":false,
                "contain30DayDeliveryService":false,
                "canApplyInstallment":false,
                "extra":{
                    "sales":247,
                    "isFreePost":true,
                    "express":"全国包邮",
                    "address":"广东佛山",
                    "onSaleTime":0,
                    "isLiveSeckill":false
                },
                "officialRecommend":{

                },
                "limitDiscountInfo":{

                },
                "lowPrice":"142.72",
                "highPrice":"142.72",
                "lowNowPrice":"99.90",
                "highNowPrice":"99.90",
                "nowTime":1586846585,
                "titleTags":[

                ],
                "titleTagsV2":[

                ],
                "picTags":[

                ],
                "pickforme":{
                    "name":"帮我选",
                    "icon":"https://s10.mogucdn.com/mlcdn/c45406/191218_762ibk3def84blec68cbe4le770df_54x54.png",
                    "link":"https://h5.mogu.com/pickforme/launch/index.html?itemId=1me7hv4&acm=3.mce.1_10_1nh28.143035.0.mXFLHrW74wAda.pos_0-m_547572-sd_119",
                    "acm":"3.mce.1_10_1nh28.143035.0.mXFLHrW74wAda.pos_0-m_547572-sd_119"
                }
            },
            "platformCoupons":{
                "bonusCount":0,
                "isBonusItem":false
            },
            "saleTextInfo":{
                "name":"slogan"
            },
            "priceInfo":{
                "nowPrice":"99.90",
                "oldPrice":"142.72",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"7折",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "diamondInfo":{
                "diamondPrice":"99.90",
                "normalPrice":"99.90",
                "state":3,
                "currency":"¥",
                "backgroundImage":"https://s11.mogucdn.com/mlcdn/c45406/170728_2740cc0db684ccfg34i2323gak715_751x81.png",
                "priceTitle":"限时优惠",
                "arrowTitle":"豪华黄钻专享价"
            },
            "normalCountdown":{
                "businessType":"",
                "isWarmUp":false,
                "nowTime":1586846585,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "shopInfo":{
                "score":[
                    {
                        "name":"描述相符",
                        "score":4.06,
                        "isBetter":false
                    },
                    {
                        "name":"质量满意",
                        "score":4.06,
                        "isBetter":false
                    }
                ],
                "services":[
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"退货补运费",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927",
                        "desc":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"延误必赔",
                        "desc":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"7天无理由退货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892",
                        "desc":"物流签收后7天内买家可无理由退货，需满足退货条件"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"72小时发货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893",
                        "desc":""
                    }
                ],
                "categories":[
                    {
                        "name":"时尚两件套装",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20294567"
                    },
                    {
                        "name":"短裤/九分裤长裤",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20331275"
                    },
                    {
                        "name":"外套",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20341425"
                    },
                    {
                        "name":"大码女装",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20360535"
                    },
                    {
                        "name":"大码女装1",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20360536"
                    },
                    {
                        "name":"大码女装2",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20360541"
                    },
                    {
                        "name":"裤子",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20360543"
                    },
                    {
                        "name":"裙子",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20360998"
                    },
                    {
                        "name":"上衣/毛衣",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20361922"
                    },
                    {
                        "name":"连衣裙",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20362984"
                    },
                    {
                        "name":"半身裙",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20362985"
                    },
                    {
                        "name":"T恤",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20362986"
                    },
                    {
                        "name":"衬衫",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20362987"
                    },
                    {
                        "name":"毛衣/针织衫",
                        "link":"http://shop.mogu.com/1172uj7q/list/index?categoryId=20370486"
                    }
                ],
                "cFans":"3780",
                "cSells":"26228",
                "isMarked":false,
                "cGoods":39,
                "userId":"17dn21e",
                "shopLogo":"https://s11.mogucdn.com/mlcdn/c45406/170911_24ll869fgh15b7fkajc91kk0ifddh_200x200.jpg",
                "name":"春风十里只为你",
                "shopId":"1172uj7q",
                "type":1,
                "level":2,
                "levelDescV2":"推荐指数",
                "shopUrl":"//m.mogu.com/v8/meili/shop?shopid=1172uj7q",
                "saleDesc":"在架商品 ",
                "saleDescV2":"在架商品 39",
                "shopLabels":[
                    {
                        "id":201,
                        "text":"3780人关注"
                    },
                    {
                        "id":303,
                        "text":"累计销量2.6万+"
                    }
                ],
                "dynShopLabels":[

                ],
                "shopLabelPriority":"101,102,201,301,302,303,401,402,501,502,601,602"
            },
            "preSaleInfo":"",
            "detailInfo":{
                "splitDetailImage":true,
                "desc":"牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子",
                "detailImage":[
                    {
                        "desc":"",
                        "key":"穿着效果",
                        "anchor":"model_img",
                        "list":[
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_0f176iea0hk22a8fe8fek328e68b8_800x800.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_07d3155fg1e090gakl3g66l9h918j_750x418.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_7fc3lh8afbic14edhg355k6il230f_750x561.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_1j2a6g0bk1k0lhlekhj2hje1d7d2c_750x1100.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_6f4816b2la82bkkd2ddb2filja67f_750x2105.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_56h3cb9c899cbli558b48d09j11ag_750x1250.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_3le1bdb32e3i15413bb0ldgh6aibj_750x1000.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_82bk88cg98b8c9kk1cg738i6i5351_750x1250.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_0dh97e6g3b60f2123cbj89idb447e_750x1000.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_6lck2352lg07hl1l211i1bdhhagg2_750x1000.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_6ebfgfg4lg8ff73ej502aka86fjc5_750x1250.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_3225ikcca8hl7f4j583bl41el3d6h_750x1250.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_73l58d761184gki07egca6f1ad14e_750x1250.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190304_4da23j3hil494dii8id53546iha35_750x1250.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_16l5e19243ia3eelfddf573b385dh_750x1000.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_0f79iaf4gfj823k9k3j27g2g656ii_750x1250.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_274bgfheef5924hab8d038d6g2jh2_750x1250.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_6i6f33bl358kal7j0hh2ll1h14ia7_750x1000.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190304_33cj0eld97fiffk8ekfa4i8hjfa8c_750x1000.jpg",
                            "https://s11.mogucdn.com/mlcdn/c024f5/190417_2d51ljj2a42lddkg49ibag494g3ca_1125x540.png"
                        ]
                    }
                ]
            },
            "countdownInfo":{
                "businessType":"NORMAL",
                "isWarmUp":false,
                "nowTime":1586846585,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "topImages":[
                "https://s11.mogucdn.com/mlcdn/c45406/190304_66j0l6766ib8951i886240f7lbiid_640x960.jpg",
                "https://s11.mogucdn.com/mlcdn/c45406/190304_6i10ff44jklb6c8747ii378gcf2e4_640x960.jpg",
                "https://s11.mogucdn.com/mlcdn/c45406/190304_126j1dkafldfab222hff7h3270420_640x960.jpg"
            ],
            "normalShareInfo":{
                "title":"牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子",
                "content":"亲爱的～这件宝贝不错哦，快进来看看吧～",
                "url":"//h5.mogu.com/detail-normal/index.html?itemId=1me7hv4&from=share",
                "imageUrl":"https://s11.mogucdn.com/mlcdn/c45406/190304_66j0l6766ib8951i886240f7lbiid_640x960.jpg"
            },
            "itemParams":{
                "info":{
                    "set":{
                        "图案":"抽象图案",
                        "裙型":"其他",
                        "颜色":"浅蓝色",
                        "腰型":"高腰",
                        "尺码":"S,XL,L,M",
                        "季节":"春秋",
                        "材质":"其他",
                        "组合形式":"单件",
                        "领型":"其他领型",
                        "裙长":"中裙（91-105cm）",
                        "袖长":"长袖",
                        "风格":"通勤（OL）",
                        "潮流":"韩系"
                    },
                    "key":"产品参数",
                    "anchor":"product_info"
                },
                "rule":{
                    "tables":[
                        [
                            [
                                "尺码",
                                "号型",
                                "裙长",
                                "肩宽",
                                "胸围",
                                "袖长"
                            ],
                            [
                                "S",
                                "155/76B",
                                "100",
                                "40",
                                "96",
                                "54"
                            ],
                            [
                                "M",
                                "160/80B",
                                "102",
                                "42",
                                "100",
                                "55"
                            ],
                            [
                                "L",
                                "165/84B",
                                "104",
                                "44",
                                "104",
                                "56"
                            ],
                            [
                                "XL",
                                "170/88B",
                                "106",
                                "46",
                                "108",
                                "57"
                            ]
                        ]
                    ],
                    "key":"尺码说明",
                    "anchor":"size_info",
                    "disclaimer":"※ 以上尺寸为实物人工测量，因测量方式不同会有1-2cm误差，相关数据仅作参考，以收到实物为准。"
                }
            },
            "normalPrice":{
                "nowPrice":"99.90",
                "oldPrice":"142.72",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"7折",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "itemServices":{
                "services":[
                    {
                        "name":"72小时发货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893"
                    },
                    {
                        "name":"7天无理由退货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"物流签收后7天内买家可无理由退货，需满足退货条件",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892"
                    },
                    {
                        "name":"延误必赔",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "name":"退货补运费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927"
                    },
                    {
                        "name":"白付美分期购",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"白付美分期购：在我的钱包 →白付美页面开通即可使用分期购。本月消费，分3/6/12期还款，每月只还一点点，轻松享受大牌好货。（分12期只对部分用户开放。）"
                    }
                ],
                "columns":[
                    {
                        "name":"sales",
                        "desc":"销量 247",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    },
                    {
                        "name":"express",
                        "desc":"免邮费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    },
                    {
                        "name":"address",
                        "desc":"广东佛山",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    }
                ]
            },
            "skuInfo":{
                "itemId":"1me7hv4",
                "img":"https://s11.mogucdn.com/mlcdn/c45406/190304_66j0l6766ib8951i886240f7lbiid_640x960.jpg",
                "isJdItem":false,
                "title":"牛仔连衣裙女春秋季新款韩版2019时尚高腰显瘦chic单排扣收腰中长款裙子",
                "skus":[
                    {
                        "stockId":"11966hle",
                        "xdSkuId":"11966hle",
                        "price":14272,
                        "nowprice":9990,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190304_006he143k7jd0jdh0ggah4a16014d_640x960.jpg",
                        "currency":"¥",
                        "stock":145,
                        "style":"浅蓝色",
                        "color":"",
                        "size":"S",
                        "styleId":1,
                        "sizeId":100,
                        "sizeType":"155/76B"
                    },
                    {
                        "stockId":"11966hlg",
                        "xdSkuId":"11966hlg",
                        "price":14272,
                        "nowprice":9990,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190304_006he143k7jd0jdh0ggah4a16014d_640x960.jpg",
                        "currency":"¥",
                        "stock":146,
                        "style":"浅蓝色",
                        "color":"",
                        "size":"M",
                        "styleId":1,
                        "sizeId":101,
                        "sizeType":"160/80B"
                    },
                    {
                        "stockId":"11966hli",
                        "xdSkuId":"11966hli",
                        "price":14272,
                        "nowprice":9990,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190304_006he143k7jd0jdh0ggah4a16014d_640x960.jpg",
                        "currency":"¥",
                        "stock":151,
                        "style":"浅蓝色",
                        "color":"",
                        "size":"L",
                        "styleId":1,
                        "sizeId":102,
                        "sizeType":"165/84B"
                    },
                    {
                        "stockId":"11966hlk",
                        "xdSkuId":"11966hlk",
                        "price":14272,
                        "nowprice":9990,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190304_006he143k7jd0jdh0ggah4a16014d_640x960.jpg",
                        "currency":"¥",
                        "stock":172,
                        "style":"浅蓝色",
                        "color":"",
                        "size":"XL",
                        "styleId":1,
                        "sizeId":103,
                        "sizeType":"170/88B"
                    }
                ],
                "props":[
                    {
                        "label":"颜色",
                        "list":[
                            {
                                "default":false,
                                "styleId":1,
                                "name":"浅蓝色",
                                "index":1,
                                "type":"style"
                            }
                        ],
                        "isDefault":false
                    },
                    {
                        "label":"尺码",
                        "list":[
                            {
                                "sizeId":100,
                                "default":false,
                                "name":"S",
                                "index":100,
                                "type":"size"
                            },
                            {
                                "sizeId":101,
                                "default":false,
                                "name":"M",
                                "index":101,
                                "type":"size"
                            },
                            {
                                "sizeId":102,
                                "default":false,
                                "name":"L",
                                "index":102,
                                "type":"size"
                            },
                            {
                                "sizeId":103,
                                "default":false,
                                "name":"XL",
                                "index":103,
                                "type":"size"
                            }
                        ],
                        "isDefault":false
                    }
                ],
                "styleKey":"颜色",
                "sizeKey":"尺码",
                "priceRange":"¥99.90",
                "defaultPrice":"¥99.90",
                "totalStock":614,
                "canInstallment":false,
                "addressInfo":{

                }
            }
        }
    },
    "needHeaderCookie":false
}
