export var pd1 = {
    "api":"http.detail.api",
    "v":"1",
    "ret":"SUCCESS",
    "data":{
        "status":{
            "code":1001,
            "msg":""
        },
        "result":{
            "userInfo":{
                "userId":"13swaiu",
                "isLogin":false,
                "isSelf":false,
                "admin":false,
                "shopId":"1p3mnc",
                "sellerId":"13swaiu"
            },
            "liveInfo":{

            },
            "rateLookInfo":{

            },
            "rateInfo":{
                "list":[
                    {
                        "user":{
                            "uname":"阿乐大大",
                            "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/180929_22k2523l220ledc4icik9gk7b0862_400x400.jpg",
                            "profileUrl":""
                        },
                        "rateId":"117x9wds",
                        "content":"衣服还是不错的，酷酷的",
                        "created":1554787646,
                        "isAnonymous":0,
                        "style":"颜色:黑色 尺码:S ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "extraInfo":[
                            "身高: 160 cm",
                            "体重: 43 kg",
                            "是否合身: 偏大 "
                        ],
                        "isBuyerShow":false,
                        "sizeInfo":{
                            "weight":"43kg",
                            "height":"160cm",
                            "desc":"偏大 "
                        }
                    },
                    {
                        "user":{
                            "uname":"h08k6l",
                            "avatar":"https://s5.mogucdn.com/new1/v1/bdefaultavatar/03.jpg",
                            "profileUrl":""
                        },
                        "rateId":"1195gpyi",
                        "content":"衣服买回来穿不了，衣袖还是反的，扣子都弄不上。发照片给商家还一个劲说没问题。看不到衣服我返回来都是揪起的？",
                        "created":1570679269,
                        "isAnonymous":0,
                        "style":"颜色:黑色 尺码:XS ",
                        "isEmpty":1,
                        "level":"",
                        "canExplain":false,
                        "isBuyerShow":false
                    }
                ],
                "cRate":119,
                "imgTotal":4,
                "rateTags":[

                ],
                "sales":804
            },
            "itemInfo":{
                "desc":"黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女",
                "title":"黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女",
                "itemId":"1mencru",
                "isFaved":false,
                "isShareIntegral":false,
                "cFav":5259,
                "state":0,
                "saleStartTime":0,
                "saleType":0,
                "seo":{
                    "keywords":"黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女",
                    "wap_url":"//m.mogujie.com/x6/detail/1mencru",
                    "description":"来自蘑菇街优店西装_上装_女装_服饰鞋包家黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女的黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女，发现当季女装和魅力生活服饰搭配心得。",
                    "alternate":"//m.mogujie.com/x6/detail/1mencru",
                    "links":"null",
                    "canonical":"//shop.mogujie.com/detail/1mencru",
                    "seo_noindex":"0",
                    "title":"【黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女】-女装-西装_上装_女装_服饰鞋包-魅力生活服饰-蘑菇街优店"
                },
                "type":8,
                "priceChannel":0,
                "virtualItemType":0,
                "isMedicalBeautyVirtualItem":false,
                "isVirtualCouponItem":false,
                "isVirtualItem":false,
                "isJdItem":false,
                "inSpringFestival":false,
                "isSpringFestivalShutdownItem":false,
                "contain30DayDeliveryService":false,
                "canApplyInstallment":false,
                "extra":{
                    "sales":804,
                    "isFreePost":true,
                    "express":"全国包邮",
                    "address":"广东佛山",
                    "onSaleTime":0,
                    "isLiveSeckill":false
                },
                "officialRecommend":{

                },
                "limitDiscountInfo":{

                },
                "lowPrice":"141.43",
                "highPrice":"141.43",
                "lowNowPrice":"99.00",
                "highNowPrice":"99.00",
                "nowTime":1586770799,
                "titleTags":[

                ],
                "titleTagsV2":[

                ],
                "picTags":[

                ],
                "pickforme":{
                    "name":"帮我选",
                    "icon":"https://s10.mogucdn.com/mlcdn/c45406/191218_762ibk3def84blec68cbe4le770df_54x54.png",
                    "link":"https://h5.mogu.com/pickforme/launch/index.html?itemId=1mencru&acm=3.mce.1_10_1nh28.143035.0.ky4jrrW1Wy6pN.pos_0-m_547572-sd_119",
                    "acm":"3.mce.1_10_1nh28.143035.0.ky4jrrW1Wy6pN.pos_0-m_547572-sd_119"
                }
            },
            "platformCoupons":{
                "bonusCount":0,
                "isBonusItem":false
            },
            "saleTextInfo":{
                "name":"slogan"
            },
            "priceInfo":{
                "nowPrice":"99.00",
                "oldPrice":"141.43",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"7折",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "diamondInfo":{
                "diamondPrice":"99.00",
                "normalPrice":"99.00",
                "state":3,
                "currency":"¥",
                "backgroundImage":"https://s11.mogucdn.com/mlcdn/c45406/170728_2740cc0db684ccfg34i2323gak715_751x81.png",
                "priceTitle":"限时优惠",
                "arrowTitle":"豪华黄钻专享价"
            },
            "normalCountdown":{
                "businessType":"",
                "isWarmUp":false,
                "nowTime":1586770799,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "shopInfo":{
                "score":[
                    {
                        "name":"描述相符",
                        "score":4.48,
                        "isBetter":false
                    },
                    {
                        "name":"质量满意",
                        "score":4.48,
                        "isBetter":false
                    }
                ],
                "services":[
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"退货补运费",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927",
                        "desc":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"延误必赔",
                        "desc":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"7天无理由退货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892",
                        "desc":"物流签收后7天内买家可无理由退货，需满足退货条件"
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"全国包邮",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=895",
                        "desc":""
                    },
                    {
                        "icon":"https://s11.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "name":"72小时发货",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893",
                        "desc":""
                    }
                ],
                "categories":[
                    {
                        "name":"裤子",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20346481"
                    },
                    {
                        "name":"上衣",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20346484"
                    },
                    {
                        "name":"外套",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20346485"
                    },
                    {
                        "name":"时尚套装",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20346486"
                    },
                    {
                        "name":"牛仔裤",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350418"
                    },
                    {
                        "name":"短裤",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350419"
                    },
                    {
                        "name":"九分裤",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350420"
                    },
                    {
                        "name":"卫衣",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350423"
                    },
                    {
                        "name":"针织衫/毛衣",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350424"
                    },
                    {
                        "name":"T恤/衬衫",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350425"
                    },
                    {
                        "name":"棉服/羽绒服",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350426"
                    },
                    {
                        "name":"马甲",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350427"
                    },
                    {
                        "name":"风衣",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350428"
                    },
                    {
                        "name":"毛呢外套",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350429"
                    },
                    {
                        "name":"开衫",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350430"
                    },
                    {
                        "name":"其他外套",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20350431"
                    },
                    {
                        "name":"雪纺衫/蕾丝衫",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20356838"
                    },
                    {
                        "name":"牛仔外套",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20356858"
                    },
                    {
                        "name":"防晒衫",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20356915"
                    },
                    {
                        "name":"防晒衣",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20356916"
                    },
                    {
                        "name":"实拍定制系列",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20377769"
                    },
                    {
                        "name":"短袖",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20382930"
                    },
                    {
                        "name":"休闲裤",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20382934"
                    },
                    {
                        "name":"半身裙",
                        "link":"http://shop.mogu.com/1p3mnc/list/index?categoryId=20382936"
                    }
                ],
                "cFans":"10498",
                "cSells":"58202",
                "isMarked":false,
                "cGoods":106,
                "userId":"13swaiu",
                "shopLogo":"https://s11.mogucdn.com/mlcdn/c45406/170615_55kh3kkh08chid38c6438cb8kbj17_640x640.jpg",
                "name":"魅力生活服饰",
                "shopId":"1p3mnc",
                "type":1,
                "level":3,
                "levelDescV2":"推荐指数",
                "shopUrl":"//m.mogu.com/v8/meili/shop?shopid=1p3mnc",
                "saleDesc":"在架商品 ",
                "saleDescV2":"在架商品 106",
                "shopLabels":[
                    {
                        "id":201,
                        "text":"1.0万人关注"
                    },
                    {
                        "id":303,
                        "text":"累计销量5.8万+"
                    },
                    {
                        "id":602,
                        "text":"3年老字号"
                    }
                ],
                "dynShopLabels":[

                ],
                "shopLabelPriority":"101,102,201,301,302,303,401,402,501,502,601,602"
            },
            "preSaleInfo":"",
            "detailInfo":{
                "splitDetailImage":true,
                "desc":"黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女",
                "detailImage":[
                    {
                        "desc":"",
                        "key":"穿着效果",
                        "anchor":"model_img",
                        "list":[
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_073hbli02hehla87b2bek00fb0el7_750x860.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_65f73781lj49c044a18g47a2lahkc_750x860.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_7a4a9k8c97l97906ljj955a9bh8aj_750x709.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_3dcid68307a0l113di61ka1kd79el_750x940.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_8bldciefe71bjl3dd53j9l914ei3j_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_81l68569178cfgai0jle5la4cg541_750x860.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_2j41a7996agk8ef9485h458838hce_750x860.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_70ak59ai083idlc5k312bblhe1ged_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_29d6e1b88h323hi281iadic839bih_750x1110.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_2afe6g3c72b54al7bb3ljf0alabbj_750x1110.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_338509g0klglc2lb33i64b65i59de_750x860.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_89a6ff1b80f6f570ad98068497i9i_750x860.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_14eah622g3kc1d0b9fj41kjda680k_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_57f77186l7il318ff7f0hjh6jb652_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_1b01976e77hkjiiiie27hb9g6deef_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_8bgc5f3i660g6jdh87fk5k5754i80_750x860.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_7ij49b3g6i81chkd59hca4i8hade0_750x860.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_618c25g1gba6d3dkbljhj4egahiij_750x860.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_54j71l539a53ch5h08k54d70ak3le_750x860.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_686ajc0514i702l5ak38ckga91ac3_750x1110.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_21al8j20l57l129225c9ac325ii9e_750x860.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_8g170h06e830h2k1cc53c6lj6g69k_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_1d47e636i62la7b3k9abd8h9b648k_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_2l87gli70299jjj2d2l78j6ldk83b_750x1110.jpg",
                            "https://s5.mogucdn.com/mlcdn/c45406/190316_0b836l9142jd594jf4d98407cajbc_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c45406/190316_60afhf6j8cg8l69f59j15gd5g5ed1_750x1110.jpg",
                            "https://s11.mogucdn.com/mlcdn/c024f5/190417_2d51ljj2a42lddkg49ibag494g3ca_1125x540.png"
                        ]
                    }
                ]
            },
            "countdownInfo":{
                "businessType":"NORMAL",
                "isWarmUp":false,
                "nowTime":1586770799,
                "countdown":0,
                "image":"",
                "titleColor":"#FFFFFF",
                "priceColor":"#FFFFFF",
                "activityBanner":"",
                "activityBannerLink":"",
                "titleIcon":"",
                "isHideRightCountdown":false,
                "text":"",
                "isCountdomShow":true,
                "isPriceShow":false
            },
            "topImages":[
                "https://s5.mogucdn.com/mlcdn/c45406/190316_7haci91l5al9cj9hg07gk19j1ah6c_640x960.jpg",
                "https://s5.mogucdn.com/mlcdn/c45406/190316_1dk1le9kal41kg71ai6lk019bj6bc_640x960.jpg",
                "https://s11.mogucdn.com/mlcdn/c45406/190316_2d6bi6211lbljcj5d0dgfl8iilc72_640x960.jpg",
                "https://s11.mogucdn.com/mlcdn/c45406/190316_4dk8clk57ib3dd926eb9hdilbg9ec_640x960.jpg"
            ],
            "normalShareInfo":{
                "title":"黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女",
                "content":"亲爱的～这件宝贝不错哦，快进来看看吧～",
                "url":"//h5.mogu.com/detail-normal/index.html?itemId=1mencru&from=share",
                "imageUrl":"https://s5.mogucdn.com/mlcdn/c45406/190316_7haci91l5al9cj9hg07gk19j1ah6c_640x960.jpg"
            },
            "itemParams":{
                "info":{
                    "set":{
                        "厚薄":"普通",
                        "颜色":"黑色,绿色,杏色",
                        "尺码":"S,XL,XS,L,M",
                        "衣长":"常规款（51-65cm）",
                        "版型":"宽松",
                        "季节":"夏季",
                        "材质":"涤纶",
                        "领型":"其他领型",
                        "袖长":"长袖",
                        "风格":"简约"
                    },
                    "key":"产品参数",
                    "anchor":"product_info"
                },
                "rule":{
                    "tables":[
                        [
                            [
                                "尺码",
                                "号型",
                                "衣长（前）",
                                "肩宽",
                                "胸围",
                                "袖长"
                            ],
                            [
                                "XS",
                                "无号型",
                                "70",
                                "48.5",
                                "109",
                                "53.5"
                            ],
                            [
                                "S",
                                "无号型",
                                "71",
                                "49.5",
                                "113",
                                "54.5"
                            ],
                            [
                                "M",
                                "无号型",
                                "72",
                                "50.5",
                                "117",
                                "55.5"
                            ],
                            [
                                "L",
                                "无号型",
                                "73",
                                "51.5",
                                "121",
                                "56.5"
                            ],
                            [
                                "XL",
                                "无号型",
                                "74",
                                "52.5",
                                "125",
                                "57.5"
                            ]
                        ]
                    ],
                    "key":"尺码说明",
                    "anchor":"size_info",
                    "disclaimer":"※ 以上尺寸为实物人工测量，因测量方式不同会有1-2cm误差，相关数据仅作参考，以收到实物为准。"
                }
            },
            "normalPrice":{
                "nowPrice":"99.00",
                "oldPrice":"141.43",
                "highNowPrice":"",
                "priceSplit":"~",
                "currency":"¥",
                "priceColor":"#333333",
                "priceTags":[
                    {
                        "text":"7折",
                        "bgColor":"#FFE8EE",
                        "textColor":"#FF2255"
                    }
                ],
                "prePriceTag":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPrice":"",
                "eventPriceDesc":{
                    "bgColor":"#FFE8EE",
                    "textColor":"#FF2255"
                },
                "eventPriceColor":"#FF2255",
                "eventTags":[

                ],
                "mobilePrice":"",
                "mobileDownloadLink":"",
                "eventDesc":"",
                "extraDesc":""
            },
            "itemServices":{
                "services":[
                    {
                        "name":"72小时发货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=893"
                    },
                    {
                        "name":"7天无理由退货",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"物流签收后7天内买家可无理由退货，需满足退货条件",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=892"
                    },
                    {
                        "name":"延误必赔",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"极速发货、送货保障，若发货时间晚于商家承诺时间或快递派送时间晚于平台标准，可获得延误补贴。"
                    },
                    {
                        "name":"退货补运费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"用户发起退货且绑定提现银行卡，可获6-18元运费补贴",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=927"
                    },
                    {
                        "name":"白付美分期购",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"白付美分期购：在我的钱包 →白付美页面开通即可使用分期购。本月消费，分3/6/12期还款，每月只还一点点，轻松享受大牌好货。（分12期只对部分用户开放。）"
                    },
                    {
                        "name":"全国包邮",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png",
                        "content":"",
                        "link":"https://www.mogu.com/rule/mogu?categoryId=326&ruleId=895"
                    }
                ],
                "columns":[
                    {
                        "name":"sales",
                        "desc":"销量 804",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    },
                    {
                        "name":"express",
                        "desc":"免邮费",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    },
                    {
                        "name":"address",
                        "desc":"广东佛山",
                        "icon":"https://s10.mogucdn.com/mlcdn/c45406/180417_25kbfg1c3hdbd120394ji4b11bk2k_36x36.png"
                    }
                ]
            },
            "skuInfo":{
                "itemId":"1mencru",
                "img":"https://s5.mogucdn.com/mlcdn/c45406/190316_7haci91l5al9cj9hg07gk19j1ah6c_640x960.jpg",
                "isJdItem":false,
                "title":"黑色外套2019春夏季新款韩版宽松显瘦气质百搭简约小个子休闲英伦风西装风衣外套女",
                "skus":[
                    {
                        "stockId":"119bfd8e",
                        "xdSkuId":"119bfd8e",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_22djbg54l2gl2l7bake42l5jdlbcb_640x960.jpg",
                        "currency":"¥",
                        "stock":198,
                        "style":"黑色",
                        "color":"#000000",
                        "size":"XS",
                        "styleId":1,
                        "sizeId":100,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8g",
                        "xdSkuId":"119bfd8g",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_22djbg54l2gl2l7bake42l5jdlbcb_640x960.jpg",
                        "currency":"¥",
                        "stock":164,
                        "style":"黑色",
                        "color":"#000000",
                        "size":"S",
                        "styleId":1,
                        "sizeId":101,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8i",
                        "xdSkuId":"119bfd8i",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_22djbg54l2gl2l7bake42l5jdlbcb_640x960.jpg",
                        "currency":"¥",
                        "stock":116,
                        "style":"黑色",
                        "color":"#000000",
                        "size":"M",
                        "styleId":1,
                        "sizeId":102,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8k",
                        "xdSkuId":"119bfd8k",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_22djbg54l2gl2l7bake42l5jdlbcb_640x960.jpg",
                        "currency":"¥",
                        "stock":148,
                        "style":"黑色",
                        "color":"#000000",
                        "size":"L",
                        "styleId":1,
                        "sizeId":103,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8m",
                        "xdSkuId":"119bfd8m",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_22djbg54l2gl2l7bake42l5jdlbcb_640x960.jpg",
                        "currency":"¥",
                        "stock":190,
                        "style":"黑色",
                        "color":"#000000",
                        "size":"XL",
                        "styleId":1,
                        "sizeId":104,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd86",
                        "xdSkuId":"119bfd86",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_8e7h2cl8b28ekf8ad878b440662h4_750x860.jpg",
                        "currency":"¥",
                        "stock":292,
                        "style":"杏色",
                        "color":"#ffa631",
                        "size":"XS",
                        "styleId":2,
                        "sizeId":100,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd84",
                        "xdSkuId":"119bfd84",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_8e7h2cl8b28ekf8ad878b440662h4_750x860.jpg",
                        "currency":"¥",
                        "stock":296,
                        "style":"杏色",
                        "color":"#ffa631",
                        "size":"S",
                        "styleId":2,
                        "sizeId":101,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd88",
                        "xdSkuId":"119bfd88",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_8e7h2cl8b28ekf8ad878b440662h4_750x860.jpg",
                        "currency":"¥",
                        "stock":295,
                        "style":"杏色",
                        "color":"#ffa631",
                        "size":"M",
                        "styleId":2,
                        "sizeId":102,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8a",
                        "xdSkuId":"119bfd8a",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_8e7h2cl8b28ekf8ad878b440662h4_750x860.jpg",
                        "currency":"¥",
                        "stock":296,
                        "style":"杏色",
                        "color":"#ffa631",
                        "size":"L",
                        "styleId":2,
                        "sizeId":103,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8c",
                        "xdSkuId":"119bfd8c",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_8e7h2cl8b28ekf8ad878b440662h4_750x860.jpg",
                        "currency":"¥",
                        "stock":297,
                        "style":"杏色",
                        "color":"#ffa631",
                        "size":"XL",
                        "styleId":2,
                        "sizeId":104,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8o",
                        "xdSkuId":"119bfd8o",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_312jljhljg8k0g3a4ifb0l57gjdhb_640x960.jpg",
                        "currency":"¥",
                        "stock":0,
                        "style":"绿色",
                        "color":"#008000",
                        "size":"XS",
                        "styleId":3,
                        "sizeId":100,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8q",
                        "xdSkuId":"119bfd8q",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_312jljhljg8k0g3a4ifb0l57gjdhb_640x960.jpg",
                        "currency":"¥",
                        "stock":0,
                        "style":"绿色",
                        "color":"#008000",
                        "size":"S",
                        "styleId":3,
                        "sizeId":101,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8s",
                        "xdSkuId":"119bfd8s",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_312jljhljg8k0g3a4ifb0l57gjdhb_640x960.jpg",
                        "currency":"¥",
                        "stock":0,
                        "style":"绿色",
                        "color":"#008000",
                        "size":"M",
                        "styleId":3,
                        "sizeId":102,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8u",
                        "xdSkuId":"119bfd8u",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_312jljhljg8k0g3a4ifb0l57gjdhb_640x960.jpg",
                        "currency":"¥",
                        "stock":0,
                        "style":"绿色",
                        "color":"#008000",
                        "size":"L",
                        "styleId":3,
                        "sizeId":103,
                        "sizeType":"无号型"
                    },
                    {
                        "stockId":"119bfd8w",
                        "xdSkuId":"119bfd8w",
                        "price":14143,
                        "nowprice":9900,
                        "img":"https://s11.mogucdn.com/mlcdn/c45406/190316_312jljhljg8k0g3a4ifb0l57gjdhb_640x960.jpg",
                        "currency":"¥",
                        "stock":0,
                        "style":"绿色",
                        "color":"#008000",
                        "size":"XL",
                        "styleId":3,
                        "sizeId":104,
                        "sizeType":"无号型"
                    }
                ],
                "props":[
                    {
                        "label":"颜色",
                        "list":[
                            {
                                "default":false,
                                "styleId":1,
                                "name":"黑色",
                                "index":1,
                                "type":"style"
                            },
                            {
                                "default":false,
                                "styleId":2,
                                "name":"杏色",
                                "index":2,
                                "type":"style"
                            },
                            {
                                "default":false,
                                "styleId":3,
                                "name":"绿色",
                                "index":3,
                                "type":"style"
                            }
                        ],
                        "isDefault":false
                    },
                    {
                        "label":"尺码",
                        "list":[
                            {
                                "sizeId":100,
                                "default":false,
                                "name":"XS",
                                "index":100,
                                "type":"size"
                            },
                            {
                                "sizeId":101,
                                "default":false,
                                "name":"S",
                                "index":101,
                                "type":"size"
                            },
                            {
                                "sizeId":102,
                                "default":false,
                                "name":"M",
                                "index":102,
                                "type":"size"
                            },
                            {
                                "sizeId":103,
                                "default":false,
                                "name":"L",
                                "index":103,
                                "type":"size"
                            },
                            {
                                "sizeId":104,
                                "default":false,
                                "name":"XL",
                                "index":104,
                                "type":"size"
                            }
                        ],
                        "isDefault":false
                    }
                ],
                "styleKey":"颜色",
                "sizeKey":"尺码",
                "priceRange":"¥99.00",
                "defaultPrice":"¥99.00",
                "totalStock":2292,
                "canInstallment":false,
                "addressInfo":{

                }
            }
        }
    },
    "needHeaderCookie":false
}
