export const rateData = {
    "api":"mwp.RateWeb.rateList",
    "v":"v3",
    "ret":"SUCCESS",
    "data":{
        "list":[
            {
                "user":{
                    "uid":"",
                    "uname":"w***5",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenbygrsggntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190528_6h14bef01210f66jljdikhj735jif_300x400.jpg"
                ],
                "rateId":"118a18yg",
                "content":"衣服质量很好！颜色很正！跟图片上面的一样！",
                "created":1559007675,
                "time":"2019年05月28日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / S",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "extraInfo":[
                    "身高: 158cm",
                    "体重: 45kg",
                    "是否合身: 合身"
                ],
                "sizeInfo":{
                    "weight":"45kg",
                    "height":"158cm",
                    "desc":"合身"
                },
                "isBuyerShow":false,
                "isFac":0,
                "facCount":1,
                "canAppend":false,
                "orderId":"11ny07q6ys6",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"w***m",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenjuhfsggntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190611_4i4i7j90b60gb2llg3j7gi2d6ki5c_300x400.jpg"
                ],
                "rateId":"118d210u",
                "content":"衣服质量挺好的，料子很柔软舒适，做工也不错！客服态度也很好，完美",
                "created":1560248441,
                "time":"2019年06月11日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / S",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":4,
                "canAppend":false,
                "orderId":"11oak1b9a3k",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"1dflvyo",
                    "uname":"真心的2005",
                    "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/190211_25k5060e4ac071cll881k14jl800d_132x132.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s11.mogucdn.com/mlcdn/c45406/190617_01hc9lfa1cff9fje1607dbf68eh2e_720x960.jpg"
                ],
                "rateId":"118e6k5i",
                "content":"衣服收到了，很符合我的审美观，穿起来感觉棒棒哒。",
                "created":1560772145,
                "time":"2019年06月17日",
                "isAnonymous":0,
                "style":"杏色衬衫（送黑色裹胸） / XL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "extraInfo":[
                    "身高: 160 cm",
                    "体重: 55 kg",
                    "是否合身: 合身 "
                ],
                "sizeInfo":{
                    "weight":"55kg",
                    "height":"160cm",
                    "desc":"合身 "
                },
                "isBuyerShow":false,
                "isFac":0,
                "facCount":2,
                "canAppend":false,
                "orderId":"11ocd1gy1xs",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"18fg0da",
                    "uname":"没有你我也不复存在",
                    "avatar":"https://s11.mogucdn.com/mlcdn/5abf39/170831_8g02jgf91lghbj6fkh68iagelkea0_640x640.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190711_45c3adiba1ca4ek6e9445b84adl0a_1080x808.jpg"
                ],
                "rateId":"118ixpfo",
                "content":"这款短裙很好的呢，也特别显瘦，胖的一直不敢穿裙子，买了这款短裙后，果断穿上了",
                "created":1562850375,
                "time":"2019年07月11日",
                "isAnonymous":0,
                "style":"侧开叉半身裙 / XXL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":2,
                "canAppend":false,
                "orderId":"11om72uqhoe",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"w***a",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrtgyjxmjrwgntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190525_6c5k82iagfa3hdk16d0h93gij11kf_300x400.jpg",
                    "https://s5.mogucdn.com/mlcdn/c45406/190525_4b24ijli8d872facehh1chf7af0ah_400x400.jpg"
                ],
                "rateId":"1188nd8i",
                "content":"百搭，穿起来很仙",
                "created":1558718169,
                "time":"2019年05月25日",
                "isAnonymous":1,
                "style":"白色衬衫（送黑色裹胸） / S",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":2,
                "canAppend":false,
                "orderId":"11ny0krsez8",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"196ltes",
                    "uname":"感觉自己圆圆哒Zara",
                    "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/171010_570aa644ce7431aae2lg5533fa0fe_640x638.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s11.mogucdn.com/mlcdn/c45406/190527_89g8ihkek2k61l1ajg92ie2f73793_640x488.jpg"
                ],
                "rateId":"1189bone",
                "content":"挺好看的",
                "created":1558931276,
                "time":"2019年05月27日",
                "isAnonymous":0,
                "style":"杏色衬衫（送黑色裹胸） / M",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":1,
                "canAppend":false,
                "orderId":"11nzzf7n2ec",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"荣***闹",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrtcnbzgbswgntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190531_68fil28ijai86h58fe7il2b8ae1bi_400x400.jpg",
                    "https://s11.mogucdn.com/mlcdn/c45406/190531_1je4k4db73lejlafclik4b873b410_400x400.jpg"
                ],
                "rateId":"118ah2lc",
                "content":"原相机拍的，挺好看的，快递也很快",
                "created":1559275812,
                "time":"2019年05月31日",
                "isAnonymous":1,
                "style":"侧开叉半身裙 / XL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":1,
                "canAppend":false,
                "orderId":"11nzzrm4xmw",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"w***b",
                    "avatar":"https://s11.mogucdn.com/p1/160105/idid_ifrtmoddmnsggntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s11.mogucdn.com/mlcdn/c45406/190525_2cea909db9deh014ake6bb854c426_400x400.jpg",
                    "https://s11.mogucdn.com/mlcdn/c45406/190525_6egk1fblgke3jc3057455kh80c62i_400x400.jpg"
                ],
                "rateId":"11898cdo",
                "content":"很好看",
                "created":1558740302,
                "time":"2019年05月25日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / L",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":5,
                "canAppend":false,
                "orderId":"11ny0ku0bxu",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"19zq0i2",
                    "uname":"怼妳嶶笶蒓屬禮貌",
                    "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/171206_17e36189kg5jj99b5j4771jdg35ba_640x640.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190609_621hall2k6cdeaai3ea1k84b7277g_1080x1440.jpg"
                ],
                "rateId":"118cewxk",
                "content":"试穿了下，感觉还不错，给个赞，准备下水洗了明天就可以穿啦！",
                "created":1559977980,
                "time":"2019年06月08日",
                "isAnonymous":0,
                "style":"杏色衬衫（送黑色裹胸） / M",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":3,
                "canAppend":false,
                "orderId":"11o8z7t3wbu",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"萌***a",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrtcnbzgbswgntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190525_506e7eag0367b2i22hk1bie4k3hji_400x400.jpg"
                ],
                "rateId":"1188z1a6",
                "content":"衣服挺好看的，轻熟风。赠送了一个裹胸，搭配裤子裙子都好看",
                "created":1558759262,
                "time":"2019年05月25日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / M",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "canAppend":false,
                "orderId":"11ny1smq8lc",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"17c4hic",
                    "uname":"w***c",
                    "avatar":"https://s11.mogucdn.com/mlcdn/5abf39/170706_0dc5kgb6c2aec5ib19aal1267dk4d_640x640.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190629_38eea151g881e30h7450lh94e6li3_307x640.jpg",
                    "https://s5.mogucdn.com/mlcdn/c45406/190629_33hld004ea6i11eb80lb77e564cfd_307x640.jpg"
                ],
                "rateId":"118glo12",
                "content":"裙子我很喜欢",
                "created":1561792296,
                "time":"2019年06月29日",
                "isAnonymous":0,
                "style":"侧开叉半身裙 / L",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "extraInfo":[
                    "是否合身: 合身"
                ],
                "sizeInfo":{
                    "desc":"合身"
                },
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "canAppend":false,
                "orderId":"11ogbqixrt0",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"w***m",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenjuhfsggntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s11.mogucdn.com/mlcdn/c45406/190609_17l68h51ef5f0b420b5a4je14ia03_225x400.jpg"
                ],
                "rateId":"118cg93a",
                "content":"超级好看，也很好搭衣服，半透不透的穿起来很好看~喜欢",
                "created":1560070108,
                "time":"2019年06月09日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / S",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "canAppend":false,
                "orderId":"11o8z7sd70g",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"w***k",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrtgyjxmjrwgntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s11.mogucdn.com/mlcdn/c45406/190609_6341dlda18fg37j586fjb7bhakif9_300x400.jpg"
                ],
                "rateId":"118ckysq",
                "content":"上身很仙女，质量很不错，美极了！",
                "created":1560054858,
                "time":"2019年06月09日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / XL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "canAppend":false,
                "orderId":"11o8z7sbvww",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"1edlmf0",
                    "uname":"菠萝油公主2011",
                    "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/190825_689ge3825ieiekhhjfjea35jckjj3_132x132.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190828_4j07jefajic4ch6l8c7l3l9g720id_810x1080.jpg"
                ],
                "rateId":"118u4riy",
                "content":"码数选大了，继续多买一件",
                "created":1566978275,
                "time":"2019年08月28日",
                "isAnonymous":0,
                "style":"杏色衬衫（送黑色吊带） / L",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "rateTagNames":"“上身效果好”",
                "canAppend":false,
                "orderId":"11oyqzhwv3w",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"1bo1hpa",
                    "uname":"wx_kwmhg52orrq1l",
                    "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/180821_8alc599k90dfe8652l42bbkk3clli_132x132.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190910_88dca642gdcd32kk6d49jg5l6d0a8_810x1080.jpg"
                ],
                "rateId":"118wszyw",
                "content":"还行吧",
                "created":1568092642,
                "time":"2019年09月10日",
                "isAnonymous":0,
                "style":"杏色衬衫（送黑色吊带） / XL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":2,
                "rateTagNames":"“发货快”",
                "canAppend":false,
                "orderId":"11p32hbocda",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"1duke18",
                    "uname":"小倩35py0h",
                    "avatar":"https://s11.mogucdn.com/mlcdn/5abf39/190618_7fdjk3ehali5jk89a0c7hke2065fe_132x132.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s11.mogucdn.com/mlcdn/c45406/190714_0ihifk304f7c0435e06g0413eci7k_3120x4160.jpg"
                ],
                "rateId":"118jdtbm",
                "content":"说实在的，在实体店里买，也不用这么贵，非常不开心的一次购买，",
                "created":1563065675,
                "time":"2019年07月14日",
                "isAnonymous":0,
                "style":"侧开叉半身裙 / XL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "explain":"亲您好！49元不可能在任何实体店买到这种好布料的西装休闲裙哦，您如果不合适的话可以联系客服申请退换货哦，退货也有运费险的呢，请不要恶意差评，谢谢亲",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":3,
                "rateTagNames":"",
                "canAppend":false,
                "orderId":"11omoubmu4s",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"",
                    "uname":"w***w",
                    "avatar":"https://s5.mogucdn.com/p1/160105/idid_ifrwenjuhfsggntfguzdambqhayde_160x160.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190527_2i7cd1bk8d3cgg2gc2a017c8h6jih_400x300.jpg"
                ],
                "rateId":"1189nfz6",
                "content":"非常喜欢很合身",
                "created":1558958344,
                "time":"2019年05月27日",
                "isAnonymous":1,
                "style":"杏色衬衫（送黑色裹胸） / XXL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":1,
                "canAppend":false,
                "orderId":"11nzz8z4ock",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"19vppes",
                    "uname":"wx_pxxotkjag6k4w",
                    "avatar":"https://s5.mogucdn.com/mlcdn/5abf39/171125_5f4glk04d80ad9di86kei09fb5agj_959x959.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190922_36gl1gfdh5bhi35h7c2h86a18d8c1_810x1080.jpg"
                ],
                "rateId":"118zykpm",
                "content":"衣服穿起来超显老，与相片不符",
                "created":1569156109,
                "time":"2019年09月22日",
                "isAnonymous":0,
                "style":"白色衬衫（送黑色吊带） / S",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":1,
                "rateTagNames":"",
                "canAppend":false,
                "orderId":"11p6x2kdbtw",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"1570j56",
                    "uname":"sftyyuuu",
                    "avatar":"https://s11.mogucdn.com/new1/v1/bdefaultavatar/05.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190719_1af4bc8hi72id73gj512lk9g549ld_3120x4160.jpg",
                    "https://s5.mogucdn.com/mlcdn/c45406/190719_6l8kl2fkdfhe9ck8k4e27650ei8l3_3120x4160.jpg"
                ],
                "rateId":"118kxi0m",
                "content":"和图片不一样，上衣打折多，裙子太短，质量不好，不透气，夏天穿不舒服",
                "created":1563506490,
                "time":"2019年07月19日",
                "isAnonymous":0,
                "style":"侧开叉半身裙 / S",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "explain":"亲您好！上衣是折痕哦，洗过就不会的了，裙子属于中裙，您觉得太短不影响二次销售可向客服申请换大一码的哦",
                "append":{
                    "content":"质量不行如何换，换到不会评论了，短的很，衣服和图片不一样，地摊货",
                    "images":[

                    ],
                    "created":1563506490
                },
                "extraInfo":[
                    "身高: 165 cm",
                    "体重: 45 kg",
                    "是否合身: 合身 "
                ],
                "sizeInfo":{
                    "weight":"45kg",
                    "height":"165cm",
                    "desc":"合身 "
                },
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "rateTagNames":"",
                "canAppend":false,
                "orderId":"11olbc631nu",
                "itemId":"1mgk2ku"
            },
            {
                "user":{
                    "uid":"1eg1we4",
                    "uname":"开心就好23fzyp",
                    "avatar":"https://s11.mogucdn.com/mlcdn/5abf39/190915_8f2ijhl7fl33b42ia2244cii9kej7_132x132.jpg",
                    "profileUrl":"",
                    "tagIndex":""
                },
                "images":[
                    "https://s5.mogucdn.com/mlcdn/c45406/190918_82cb04g2a8h280l5f8lefjj7i4i23_810x1080.jpg"
                ],
                "rateId":"118ys72w",
                "content":"选的是套装，买过来只有一件衣服。",
                "created":1568782227,
                "time":"2019年09月18日",
                "isAnonymous":0,
                "style":"杏色衬衫（送黑色吊带） / XXL",
                "canExplain":false,
                "sellerUserId":"136dz1y",
                "isBuyerShow":false,
                "isFac":0,
                "facCount":0,
                "rateTagNames":"",
                "canAppend":false,
                "orderId":"11p5vmxgocc",
                "itemId":"1mgk2ku"
            }
        ]
    },
    "needHeaderCookie":false
}

export const rateBaseInfo = {
    "total":170,
    "imageTotal":32,
    "pageSize":20,
    "currentPage":1,
    "mbook":"eyJwYWdlIjoyLCJ0cmFkZUl0ZW1JZCI6Njc5MDMzMDY3fQ==",
    "canExplain":false,
    "isEnd":false,
    "averageScore":"4.57",
    "rateScore":[
        {
            "key":"描述相符",
            "value":"4.57"
        },
        {
            "key":"商品质量",
            "value":"4.57"
        }
    ],
    "rateTags":[
        {
            "emotion":"positive",
            "property":"全部",
            "value":"全部",
            "num":440,
            "labelId":0
        },
        {
            "emotion":"positive",
            "property":"最新",
            "value":"最新",
            "num":0,
            "labelId":0
        },
        {
            "emotion":"positive",
            "property":"图片",
            "value":"有图片",
            "num":32,
            "labelId":0
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"图片描述一致",
            "num":28,
            "labelId":15
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"没有色差",
            "num":25,
            "labelId":13
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"款式好看",
            "num":24,
            "labelId":12
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"上身效果好",
            "num":24,
            "labelId":11
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"发货快",
            "num":22,
            "labelId":19
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"做工满意",
            "num":22,
            "labelId":5
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"料子很不错",
            "num":22,
            "labelId":3
        },
        {
            "emotion":"positive",
            "property":"款式",
            "value":"款式好",
            "num":21,
            "labelId":0
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"没有气味",
            "num":19,
            "labelId":9
        },
        {
            "emotion":"positive",
            "property":"rateLabel",
            "value":"质量好",
            "num":18,
            "labelId":1
        }
    ],
    "emotion":"positive",
    "property":"全部",
    "isBetter":false,
    "bottomText":"共有404位用户给出了好评！"
}
